/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/com.layer1.clients.digital.invoker/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/com.layer1.clients.digital.invoker/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DigitalAsset);
  }
}(this, function(expect, DigitalAsset) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DigitalAsset.AssetPoolApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssetPoolApi', function() {
    describe('createAssetPool', function() {
      it('should call createAssetPool successfully', function(done) {
        //uncomment below and update the code to test createAssetPool
        //instance.createAssetPool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAssetPool', function() {
      it('should call deleteAssetPool successfully', function(done) {
        //uncomment below and update the code to test deleteAssetPool
        //instance.deleteAssetPool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetPool', function() {
      it('should call getAssetPool successfully', function(done) {
        //uncomment below and update the code to test getAssetPool
        //instance.getAssetPool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetPoolBalance', function() {
      it('should call getAssetPoolBalance successfully', function(done) {
        //uncomment below and update the code to test getAssetPoolBalance
        //instance.getAssetPoolBalance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetPoolMaxWithdrawableAmount', function() {
      it('should call getAssetPoolMaxWithdrawableAmount successfully', function(done) {
        //uncomment below and update the code to test getAssetPoolMaxWithdrawableAmount
        //instance.getAssetPoolMaxWithdrawableAmount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetPoolSummary', function() {
      it('should call getAssetPoolSummary successfully', function(done) {
        //uncomment below and update the code to test getAssetPoolSummary
        //instance.getAssetPoolSummary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAssetPools', function() {
      it('should call listAssetPools successfully', function(done) {
        //uncomment below and update the code to test listAssetPools
        //instance.listAssetPools(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAssetPool', function() {
      it('should call updateAssetPool successfully', function(done) {
        //uncomment below and update the code to test updateAssetPool
        //instance.updateAssetPool(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
