/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiError from '../com.layer1.clients.digital.model/ApiError';
import CreateBalanceExportRequest from '../com.layer1.clients.digital.model/CreateBalanceExportRequest';
import Export from '../com.layer1.clients.digital.model/Export';
import PaginatedExports from '../com.layer1.clients.digital.model/PaginatedExports';

/**
* Export service.
* @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ExportApi
* @version 1.0.0
*/
export default class ExportApi {

    /**
    * Constructs a new ExportApi. 
    * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ExportApi
    * @class
    * @param {module:com.layer1.clients.digital.invoker/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:com.layer1.clients.digital.invoker/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createBalanceExport operation.
     * @callback module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ExportApi~createBalanceExportCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a balance export
     * Initiates a job to export balance data in the CSV format.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/CreateBalanceExportRequest} createBalanceExportRequest 
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ExportApi~createBalanceExportCallback} callback The callback function, accepting three arguments: error, data, response
     */
    createBalanceExport(createBalanceExportRequest, callback) {
      let postBody = createBalanceExportRequest;
      // verify the required parameter 'createBalanceExportRequest' is set
      if (createBalanceExportRequest === undefined || createBalanceExportRequest === null) {
        throw new Error("Missing the required parameter 'createBalanceExportRequest' when calling createBalanceExport");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['httpSignature', 'oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/digital/v1/exports', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getExport operation.
     * @callback module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ExportApi~getExportCallback
     * @param {String} error Error message, if any.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Export} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get export with a download link
     * Retrieves export details with a short-lived download link by its ID.
     * @param {String} id The ID of the export to retrieve
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ExportApi~getExportCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Export}
     */
    getExport(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getExport");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['httpSignature', 'oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Export;
      return this.apiClient.callApi(
        '/digital/v1/exports/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getExports operation.
     * @callback module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ExportApi~getExportsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/PaginatedExports>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all exports
     * Retrieves a paginated list of exports based on type and pagination settings.
     * @param {Array.<String>} type Filter exports by type
     * @param {Number} pageNumber 
     * @param {Number} pageSize 
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ExportApi~getExportsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/PaginatedExports>}
     */
    getExports(type, pageNumber, pageSize, callback) {
      let postBody = null;
      // verify the required parameter 'type' is set
      if (type === undefined || type === null) {
        throw new Error("Missing the required parameter 'type' when calling getExports");
      }
      // verify the required parameter 'pageNumber' is set
      if (pageNumber === undefined || pageNumber === null) {
        throw new Error("Missing the required parameter 'pageNumber' when calling getExports");
      }
      // verify the required parameter 'pageSize' is set
      if (pageSize === undefined || pageSize === null) {
        throw new Error("Missing the required parameter 'pageSize' when calling getExports");
      }

      let pathParams = {
      };
      let queryParams = {
        'type': this.apiClient.buildCollectionParam(type, 'multi'),
        'pageNumber': pageNumber,
        'pageSize': pageSize
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['httpSignature', 'oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PaginatedExports];
      return this.apiClient.callApi(
        '/digital/v1/exports', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
