/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiError from '../com.layer1.clients.digital.model/ApiError';
import AssetValue from '../com.layer1.clients.digital.model/AssetValue';
import EstimateTransactionFeeRequest from '../com.layer1.clients.digital.model/EstimateTransactionFeeRequest';

/**
* Fee service.
* @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/FeeApi
* @version 1.0.0
*/
export default class FeeApi {

    /**
    * Constructs a new FeeApi. 
    * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/FeeApi
    * @class
    * @param {module:com.layer1.clients.digital.invoker/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:com.layer1.clients.digital.invoker/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the estimateTransactionFee operation.
     * @callback module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/FeeApi~estimateTransactionFeeCallback
     * @param {String} error Error message, if any.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/AssetValue} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Estimate transaction fee
     * Estimate fee to send blockchain transaction
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/EstimateTransactionFeeRequest} estimateTransactionFeeRequest 
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/FeeApi~estimateTransactionFeeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/AssetValue}
     */
    estimateTransactionFee(estimateTransactionFeeRequest, callback) {
      let postBody = estimateTransactionFeeRequest;
      // verify the required parameter 'estimateTransactionFeeRequest' is set
      if (estimateTransactionFeeRequest === undefined || estimateTransactionFeeRequest === null) {
        throw new Error("Missing the required parameter 'estimateTransactionFeeRequest' when calling estimateTransactionFee");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['httpSignature', 'oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AssetValue;
      return this.apiClient.callApi(
        '/digital/v1/fee-estimate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
