/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiError from '../com.layer1.clients.digital.model/ApiError';
import Network from '../com.layer1.clients.digital.model/Network';

/**
* Network service.
* @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/NetworkApi
* @version 1.0.0
*/
export default class NetworkApi {

    /**
    * Constructs a new NetworkApi. 
    * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/NetworkApi
    * @class
    * @param {module:com.layer1.clients.digital.invoker/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:com.layer1.clients.digital.invoker/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getNetworks operation.
     * @callback module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/NetworkApi~getNetworksCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Network>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all networks
     * Get all supported networks and their assets. By default, only enabled networks are returned.
     * @param {Object} opts Optional parameters
     * @param {Boolean} [includeDisabled = false)] Include disabled networks in the response
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/NetworkApi~getNetworksCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Network>}
     */
    getNetworks(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'includeDisabled': opts['includeDisabled']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['httpSignature', 'oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Network];
      return this.apiClient.callApi(
        '/digital/v1/networks', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
