/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiError from '../com.layer1.clients.digital.model/ApiError';
import ReturnRequest from '../com.layer1.clients.digital.model/ReturnRequest';
import TransactionRequest from '../com.layer1.clients.digital.model/TransactionRequest';

/**
* Return service.
* @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ReturnApi
* @version 1.0.0
*/
export default class ReturnApi {

    /**
    * Constructs a new ReturnApi. 
    * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ReturnApi
    * @class
    * @param {module:com.layer1.clients.digital.invoker/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:com.layer1.clients.digital.invoker/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createReturnTransactionRequest operation.
     * @callback module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ReturnApi~createReturnTransactionRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create return transaction request
     * Create a new blockchain transaction meant to return previously deposited funds
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/ReturnRequest} returnRequest 
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.api/ReturnApi~createReturnTransactionRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionRequest}
     */
    createReturnTransactionRequest(returnRequest, callback) {
      let postBody = returnRequest;
      // verify the required parameter 'returnRequest' is set
      if (returnRequest === undefined || returnRequest === null) {
        throw new Error("Missing the required parameter 'returnRequest' when calling createReturnTransactionRequest");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['httpSignature', 'oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TransactionRequest;
      return this.apiClient.callApi(
        '/digital/v1/returns', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
