/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/com.layer1.clients.digital.invoker/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/com.layer1.clients.digital.invoker/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DigitalAsset);
  }
}(this, function(expect, DigitalAsset) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DigitalAsset.Network();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Network', function() {
    it('should create an instance of Network', function() {
      // uncomment below and update the code to test Network
      //var instance = new DigitalAsset.Network();
      //expect(instance).to.be.a(DigitalAsset.Network);
    });

    it('should have the property network (base name: "network")', function() {
      // uncomment below and update the code to test the property network
      //var instance = new DigitalAsset.Network();
      //expect(instance).to.be();
    });

    it('should have the property nativeAsset (base name: "nativeAsset")', function() {
      // uncomment below and update the code to test the property nativeAsset
      //var instance = new DigitalAsset.Network();
      //expect(instance).to.be();
    });

    it('should have the property supportedAssets (base name: "supportedAssets")', function() {
      // uncomment below and update the code to test the property supportedAssets
      //var instance = new DigitalAsset.Network();
      //expect(instance).to.be();
    });

    it('should have the property tagSupported (base name: "tagSupported")', function() {
      // uncomment below and update the code to test the property tagSupported
      //var instance = new DigitalAsset.Network();
      //expect(instance).to.be();
    });

  });

}));
