/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Balance from './Balance';

/**
 * The AssetPoolSummary model module.
 * @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/AssetPoolSummary
 * @version 1.0.0
 */
class AssetPoolSummary {
    /**
     * Constructs a new <code>AssetPoolSummary</code>.
     * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/AssetPoolSummary
     */
    constructor() { 
        
        AssetPoolSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetPoolSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/AssetPoolSummary} obj Optional instance to populate.
     * @return {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/AssetPoolSummary} The populated <code>AssetPoolSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetPoolSummary();

            if (data.hasOwnProperty('balances')) {
                obj['balances'] = ApiClient.convertToType(data['balances'], [Balance]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetPoolSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetPoolSummary</code>.
     */
    static validateJSON(data) {
        if (data['balances']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['balances'])) {
                throw new Error("Expected the field `balances` to be an array in the JSON data but got " + data['balances']);
            }
            // validate the optional field `balances` (array)
            for (const item of data['balances']) {
                Balance.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * balances summary
 * @member {Array.<module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Balance>} balances
 */
AssetPoolSummary.prototype['balances'] = undefined;






export default AssetPoolSummary;

