/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Balance model module.
 * @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Balance
 * @version 1.0.0
 */
class Balance {
    /**
     * Constructs a new <code>Balance</code>.
     * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Balance
     */
    constructor() { 
        
        Balance.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Balance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Balance} obj Optional instance to populate.
     * @return {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Balance} The populated <code>Balance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Balance();

            if (data.hasOwnProperty('network')) {
                obj['network'] = ApiClient.convertToType(data['network'], 'String');
            }
            if (data.hasOwnProperty('asset')) {
                obj['asset'] = ApiClient.convertToType(data['asset'], 'String');
            }
            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], Object);
            }
            if (data.hasOwnProperty('reserved')) {
                obj['reserved'] = ApiClient.convertToType(data['reserved'], Object);
            }
            if (data.hasOwnProperty('blockchain')) {
                obj['blockchain'] = ApiClient.convertToType(data['blockchain'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Balance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Balance</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['network'] && !(typeof data['network'] === 'string' || data['network'] instanceof String)) {
            throw new Error("Expected the field `network` to be a primitive type in the JSON string but got " + data['network']);
        }
        // ensure the json data is a string
        if (data['asset'] && !(typeof data['asset'] === 'string' || data['asset'] instanceof String)) {
            throw new Error("Expected the field `asset` to be a primitive type in the JSON string but got " + data['asset']);
        }

        return true;
    }


}



/**
 * network
 * @member {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Balance.NetworkEnum} network
 */
Balance.prototype['network'] = undefined;

/**
 * asset
 * @member {String} asset
 */
Balance.prototype['asset'] = undefined;

/**
 * @member {Object} available
 */
Balance.prototype['available'] = undefined;

/**
 * @member {Object} reserved
 */
Balance.prototype['reserved'] = undefined;

/**
 * @member {Object} blockchain
 */
Balance.prototype['blockchain'] = undefined;





/**
 * Allowed values for the <code>network</code> property.
 * @enum {String}
 * @readonly
 */
Balance['NetworkEnum'] = {

    /**
     * value: "BASE"
     * @const
     */
    "BASE": "BASE",

    /**
     * value: "BINANCE"
     * @const
     */
    "BINANCE": "BINANCE",

    /**
     * value: "BITCOIN"
     * @const
     */
    "BITCOIN": "BITCOIN",

    /**
     * value: "BITCOIN_CASH"
     * @const
     */
    "BITCOIN_CASH": "BITCOIN_CASH",

    /**
     * value: "DOGECOIN"
     * @const
     */
    "DOGECOIN": "DOGECOIN",

    /**
     * value: "ETHEREUM"
     * @const
     */
    "ETHEREUM": "ETHEREUM",

    /**
     * value: "LITECOIN"
     * @const
     */
    "LITECOIN": "LITECOIN",

    /**
     * value: "POLYGON"
     * @const
     */
    "POLYGON": "POLYGON",

    /**
     * value: "RIPPLE"
     * @const
     */
    "RIPPLE": "RIPPLE",

    /**
     * value: "SOLANA"
     * @const
     */
    "SOLANA": "SOLANA",

    /**
     * value: "TRON"
     * @const
     */
    "TRON": "TRON",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};



export default Balance;

