/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlockDetail model module.
 * @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/BlockDetail
 * @version 1.0.0
 */
class BlockDetail {
    /**
     * Constructs a new <code>BlockDetail</code>.
     * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/BlockDetail
     */
    constructor() { 
        
        BlockDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/BlockDetail} obj Optional instance to populate.
     * @return {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/BlockDetail} The populated <code>BlockDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockDetail();

            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BlockDetail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BlockDetail</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * blockchain number
 * @member {Number} number
 */
BlockDetail.prototype['number'] = undefined;

/**
 * timestamp of the block
 * @member {Date} timestamp
 */
BlockDetail.prototype['timestamp'] = undefined;






export default BlockDetail;

