/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Participant from './Participant';

/**
 * The CreateTransactionRequest model module.
 * @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/CreateTransactionRequest
 * @version 1.0.0
 */
class CreateTransactionRequest {
    /**
     * Constructs a new <code>CreateTransactionRequest</code>.
     * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/CreateTransactionRequest
     */
    constructor() { 
        
        CreateTransactionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateTransactionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/CreateTransactionRequest} obj Optional instance to populate.
     * @return {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/CreateTransactionRequest} The populated <code>CreateTransactionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTransactionRequest();

            if (data.hasOwnProperty('assetPoolId')) {
                obj['assetPoolId'] = ApiClient.convertToType(data['assetPoolId'], 'String');
            }
            if (data.hasOwnProperty('asset')) {
                obj['asset'] = ApiClient.convertToType(data['asset'], 'String');
            }
            if (data.hasOwnProperty('network')) {
                obj['network'] = ApiClient.convertToType(data['network'], 'String');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], [Participant]);
            }
            if (data.hasOwnProperty('destinations')) {
                obj['destinations'] = ApiClient.convertToType(data['destinations'], [Participant]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateTransactionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateTransactionRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['assetPoolId'] && !(typeof data['assetPoolId'] === 'string' || data['assetPoolId'] instanceof String)) {
            throw new Error("Expected the field `assetPoolId` to be a primitive type in the JSON string but got " + data['assetPoolId']);
        }
        // ensure the json data is a string
        if (data['asset'] && !(typeof data['asset'] === 'string' || data['asset'] instanceof String)) {
            throw new Error("Expected the field `asset` to be a primitive type in the JSON string but got " + data['asset']);
        }
        // ensure the json data is a string
        if (data['network'] && !(typeof data['network'] === 'string' || data['network'] instanceof String)) {
            throw new Error("Expected the field `network` to be a primitive type in the JSON string but got " + data['network']);
        }
        // ensure the json data is a string
        if (data['reference'] && !(typeof data['reference'] === 'string' || data['reference'] instanceof String)) {
            throw new Error("Expected the field `reference` to be a primitive type in the JSON string but got " + data['reference']);
        }
        if (data['sources']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sources'])) {
                throw new Error("Expected the field `sources` to be an array in the JSON data but got " + data['sources']);
            }
            // validate the optional field `sources` (array)
            for (const item of data['sources']) {
                Participant.validateJSON(item);
            };
        }
        if (data['destinations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['destinations'])) {
                throw new Error("Expected the field `destinations` to be an array in the JSON data but got " + data['destinations']);
            }
            // validate the optional field `destinations` (array)
            for (const item of data['destinations']) {
                Participant.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * asset pool id
 * @member {String} assetPoolId
 */
CreateTransactionRequest.prototype['assetPoolId'] = undefined;

/**
 * currency
 * @member {String} asset
 */
CreateTransactionRequest.prototype['asset'] = undefined;

/**
 * crypto network
 * @member {String} network
 */
CreateTransactionRequest.prototype['network'] = undefined;

/**
 * custom identifier supplied for transaction that is used to link transaction to specific customer or use case
 * @member {String} reference
 */
CreateTransactionRequest.prototype['reference'] = undefined;

/**
 * (Optional) list of addresses and amounts that fund the transaction
 * @member {Array.<module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Participant>} sources
 */
CreateTransactionRequest.prototype['sources'] = undefined;

/**
 * list of recipient addresses and amounts that benefit from the transaction
 * @member {Array.<module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Participant>} destinations
 */
CreateTransactionRequest.prototype['destinations'] = undefined;






export default CreateTransactionRequest;

