/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetValue from './AssetValue';
import BlockDetail from './BlockDetail';

/**
 * The NetworkDetail model module.
 * @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/NetworkDetail
 * @version 1.0.0
 */
class NetworkDetail {
    /**
     * Constructs a new <code>NetworkDetail</code>.
     * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/NetworkDetail
     */
    constructor() { 
        
        NetworkDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetworkDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/NetworkDetail} obj Optional instance to populate.
     * @return {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/NetworkDetail} The populated <code>NetworkDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkDetail();

            if (data.hasOwnProperty('block')) {
                obj['block'] = BlockDetail.constructFromObject(data['block']);
            }
            if (data.hasOwnProperty('fee')) {
                obj['fee'] = AssetValue.constructFromObject(data['fee']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NetworkDetail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NetworkDetail</code>.
     */
    static validateJSON(data) {
        // validate the optional field `block`
        if (data['block']) { // data not null
          BlockDetail.validateJSON(data['block']);
        }
        // validate the optional field `fee`
        if (data['fee']) { // data not null
          AssetValue.validateJSON(data['fee']);
        }

        return true;
    }


}



/**
 * block detail such as number and timestamp
 * @member {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/BlockDetail} block
 */
NetworkDetail.prototype['block'] = undefined;

/**
 * network fee on the blockchain
 * @member {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/AssetValue} fee
 */
NetworkDetail.prototype['fee'] = undefined;






export default NetworkDetail;

