/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Pageable model module.
 * @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Pageable
 * @version 1.0.0
 */
class Pageable {
    /**
     * Constructs a new <code>Pageable</code>.
     * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Pageable
     */
    constructor() { 
        
        Pageable.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Pageable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Pageable} obj Optional instance to populate.
     * @return {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Pageable} The populated <code>Pageable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Pageable();

            if (data.hasOwnProperty('pageNumber')) {
                obj['pageNumber'] = ApiClient.convertToType(data['pageNumber'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Pageable</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Pageable</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * current page number
 * @member {Number} pageNumber
 */
Pageable.prototype['pageNumber'] = undefined;

/**
 * number of items in page
 * @member {Number} pageSize
 */
Pageable.prototype['pageSize'] = undefined;






export default Pageable;

