/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Failure from './Failure';
import Participant from './Participant';

/**
 * The TransactionRequest model module.
 * @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionRequest
 * @version 1.0.0
 */
class TransactionRequest {
    /**
     * Constructs a new <code>TransactionRequest</code>.
     * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionRequest
     */
    constructor() { 
        
        TransactionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionRequest} obj Optional instance to populate.
     * @return {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionRequest} The populated <code>TransactionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionRequest();

            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
            if (data.hasOwnProperty('asset')) {
                obj['asset'] = ApiClient.convertToType(data['asset'], 'String');
            }
            if (data.hasOwnProperty('assetPoolId')) {
                obj['assetPoolId'] = ApiClient.convertToType(data['assetPoolId'], 'String');
            }
            if (data.hasOwnProperty('network')) {
                obj['network'] = ApiClient.convertToType(data['network'], 'String');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], [Participant]);
            }
            if (data.hasOwnProperty('destinations')) {
                obj['destinations'] = ApiClient.convertToType(data['destinations'], [Participant]);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('failure')) {
                obj['failure'] = Failure.constructFromObject(data['failure']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['requestId'] && !(typeof data['requestId'] === 'string' || data['requestId'] instanceof String)) {
            throw new Error("Expected the field `requestId` to be a primitive type in the JSON string but got " + data['requestId']);
        }
        // ensure the json data is a string
        if (data['asset'] && !(typeof data['asset'] === 'string' || data['asset'] instanceof String)) {
            throw new Error("Expected the field `asset` to be a primitive type in the JSON string but got " + data['asset']);
        }
        // ensure the json data is a string
        if (data['assetPoolId'] && !(typeof data['assetPoolId'] === 'string' || data['assetPoolId'] instanceof String)) {
            throw new Error("Expected the field `assetPoolId` to be a primitive type in the JSON string but got " + data['assetPoolId']);
        }
        // ensure the json data is a string
        if (data['network'] && !(typeof data['network'] === 'string' || data['network'] instanceof String)) {
            throw new Error("Expected the field `network` to be a primitive type in the JSON string but got " + data['network']);
        }
        // ensure the json data is a string
        if (data['reference'] && !(typeof data['reference'] === 'string' || data['reference'] instanceof String)) {
            throw new Error("Expected the field `reference` to be a primitive type in the JSON string but got " + data['reference']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        if (data['sources']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sources'])) {
                throw new Error("Expected the field `sources` to be an array in the JSON data but got " + data['sources']);
            }
            // validate the optional field `sources` (array)
            for (const item of data['sources']) {
                Participant.validateJSON(item);
            };
        }
        if (data['destinations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['destinations'])) {
                throw new Error("Expected the field `destinations` to be an array in the JSON data but got " + data['destinations']);
            }
            // validate the optional field `destinations` (array)
            for (const item of data['destinations']) {
                Participant.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // validate the optional field `failure`
        if (data['failure']) { // data not null
          Failure.validateJSON(data['failure']);
        }

        return true;
    }


}



/**
 * transaction request id
 * @member {String} requestId
 */
TransactionRequest.prototype['requestId'] = undefined;

/**
 * currency
 * @member {String} asset
 */
TransactionRequest.prototype['asset'] = undefined;

/**
 * asset pool id
 * @member {String} assetPoolId
 */
TransactionRequest.prototype['assetPoolId'] = undefined;

/**
 * crypto network
 * @member {String} network
 */
TransactionRequest.prototype['network'] = undefined;

/**
 * custom identifier supplied for transaction that is used to link transaction to specific customer or use case
 * @member {String} reference
 */
TransactionRequest.prototype['reference'] = undefined;

/**
 * transaction request status
 * @member {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionRequest.StatusEnum} status
 */
TransactionRequest.prototype['status'] = undefined;

/**
 * requested list of addresses and amounts that fund the transaction
 * @member {Array.<module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Participant>} sources
 */
TransactionRequest.prototype['sources'] = undefined;

/**
 * requested list of recipient addresses and amounts that benefit from the transaction
 * @member {Array.<module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Participant>} destinations
 */
TransactionRequest.prototype['destinations'] = undefined;

/**
 * transaction request type
 * @member {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionRequest.TypeEnum} type
 */
TransactionRequest.prototype['type'] = undefined;

/**
 * timestamp when transaction request was created
 * @member {Date} createdAt
 */
TransactionRequest.prototype['createdAt'] = undefined;

/**
 * timestamp when transaction request was updated
 * @member {Date} updatedAt
 */
TransactionRequest.prototype['updatedAt'] = undefined;

/**
 * failure details
 * @member {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Failure} failure
 */
TransactionRequest.prototype['failure'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
TransactionRequest['StatusEnum'] = {

    /**
     * value: "BLOCKED"
     * @const
     */
    "BLOCKED": "BLOCKED",

    /**
     * value: "CONFIRMED"
     * @const
     */
    "CONFIRMED": "CONFIRMED",

    /**
     * value: "CREATED"
     * @const
     */
    "CREATED": "CREATED",

    /**
     * value: "DETECTED"
     * @const
     */
    "DETECTED": "DETECTED",

    /**
     * value: "FAILED"
     * @const
     */
    "FAILED": "FAILED",

    /**
     * value: "FUNDS_RESERVED"
     * @const
     */
    "FUNDS_RESERVED": "FUNDS_RESERVED",

    /**
     * value: "HELD"
     * @const
     */
    "HELD": "HELD",

    /**
     * value: "REJECTED"
     * @const
     */
    "REJECTED": "REJECTED",

    /**
     * value: "SCREENING_PASSED"
     * @const
     */
    "SCREENING_PASSED": "SCREENING_PASSED",

    /**
     * value: "SCREENING_REQUESTED"
     * @const
     */
    "SCREENING_REQUESTED": "SCREENING_REQUESTED",

    /**
     * value: "SIGNED"
     * @const
     */
    "SIGNED": "SIGNED",

    /**
     * value: "SUCCESS"
     * @const
     */
    "SUCCESS": "SUCCESS",

    /**
     * value: "UNCONFIRMED"
     * @const
     */
    "UNCONFIRMED": "UNCONFIRMED",

    /**
     * value: "REPLACED"
     * @const
     */
    "REPLACED": "REPLACED",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
TransactionRequest['TypeEnum'] = {

    /**
     * value: "DEPOSIT"
     * @const
     */
    "DEPOSIT": "DEPOSIT",

    /**
     * value: "WITHDRAWAL"
     * @const
     */
    "WITHDRAWAL": "WITHDRAWAL",

    /**
     * value: "CONSOLIDATION"
     * @const
     */
    "CONSOLIDATION": "CONSOLIDATION",

    /**
     * value: "RETURN"
     * @const
     */
    "RETURN": "RETURN",

    /**
     * value: "STAKE"
     * @const
     */
    "STAKE": "STAKE",

    /**
     * value: "UNSTAKE"
     * @const
     */
    "UNSTAKE": "UNSTAKE",

    /**
     * value: "DELEGATE"
     * @const
     */
    "DELEGATE": "DELEGATE",

    /**
     * value: "UNDELEGATE"
     * @const
     */
    "UNDELEGATE": "UNDELEGATE",

    /**
     * value: "RELEASE"
     * @const
     */
    "RELEASE": "RELEASE",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};



export default TransactionRequest;

