/**
 * Digital Asset
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Failure from './Failure';

/**
 * The TransactionMetadata model module.
 * @module com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionMetadata
 * @version 1.0.0
 */
class TransactionMetadata {
    /**
     * Constructs a new <code>TransactionMetadata</code>.
     * @alias module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionMetadata
     */
    constructor() { 
        
        TransactionMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionMetadata} obj Optional instance to populate.
     * @return {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/TransactionMetadata} The populated <code>TransactionMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionMetadata();

            if (data.hasOwnProperty('failure')) {
                obj['failure'] = Failure.constructFromObject(data['failure']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionMetadata</code>.
     */
    static validateJSON(data) {
        // validate the optional field `failure`
        if (data['failure']) { // data not null
          Failure.validateJSON(data['failure']);
        }

        return true;
    }


}



/**
 * information about why the transaction failed
 * @member {module:com.layer1.clients.digital.invoker/com.layer1.clients.digital.model/Failure} failure
 */
TransactionMetadata.prototype['failure'] = undefined;






export default TransactionMetadata;

